 platform :ios, '8.0'

target 'ArchitectureProjects' do
   pod 'Realm'
   pod 'DZNEmptyDataSet'
   pod 'SDWebImage', '~>3.7.6'
   pod 'Fabric'
   pod 'Crashlytics'
   pod 'AFNetworking', '~> 2.0'
   pod 'GooglePlaces'
   pod 'SWRevealViewController', '~> 2.3'
   pod 'MBProgressHUD', '~> 0.9.2'
   pod 'GCNetworkReachability'
   pod 'IQKeyboardManager'
   pod 'Firebase/Storage'
   pod 'Firebase/Auth'
   pod 'Firebase/Messaging'
   pod 'Firebase/Database'
   pod 'SAMKeychain'

end
